# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #make sure chef is installed
  config.omnibus.chef_version = :latest

  config.vm.box = "ubuntu-12.04"

  config.vm.network "forwarded_port", guest: 80, host: 8889

  config.vm.provision :chef_solo do |chef|
    chef.data_bags_path = "data_bags"
    chef.roles_path = "roles"

    chef.add_recipe "chef-solo-search"
    chef.add_recipe "nagios"
    chef.add_recipe "nagios::server"
  end
end
